apiVersion: v1
kind: Service
metadata:
  name: nodejs-elysia
  namespace: nodejs-elysia
  labels:
    app: nodejs-elysia
spec:
  type: ClusterIP
  selector:
    app: nodejs-elysia
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
